### ISSUE TITLE
Random Crashing

### ISSUE THREAD

**Issue by cmb991** [wylanswets/homebridge-icontrol-platform#2]
Error below.  Confirmed with a hoobs developer that the issue isn’t related to hoobs or homebridge, it’s an api issue. 
![AB0CA3B3-6E4E-4271-AD0A-598CB73796D0](https://user-images.githubusercontent.com/30929454/77465103-8634dc80-6dde-11ea-971f-ac3a1963416c.png)

**Comment by wylanswets** [comment]
I have pushed an update to resolve this problematic crash by wrapping that line in a try catch.
