### ISSUE TITLE
Accessories stopped working

### ISSUE THREAD

**Issue by cmb991** [wylanswets/homebridge-icontrol-platform#6]
6/5/2020, 4:48:19 AM There was an error while communicating with iControl. Status code was 500 and error was: Error: Invalid status code 500

6/5/2020, 4:48:19 AM Stack:Error6/5/2020, 4:48:19 AM at iControl._notifyError (/home/hoobs/.hoobs/node_modules/icontrol-api/index.js:494:181)

6/5/2020, 4:48:19 AM at iControl.<anonymous> (/home/hoobs/.hoobs/node_modules/icontrol-api/index.js:486:12)

6/5/2020, 4:48:19 AM at Request.self.callback (/home/hoobs/.hoobs/node_modules/request/request.js:185:22)

6/5/2020, 4:48:19 AM at Request.emit (events.js:198:13)

6/5/2020, 4:48:19 AM at Request.<anonymous> (/home/hoobs/.hoobs/node_modules/request/request.js:1154:10)

6/5/2020, 4:48:19 AM at Request.emit (events.js:198:13)

6/5/2020, 4:48:19 AM at IncomingMessage.<anonymous> (/home/hoobs/.hoobs/node_modules/request/request.js:1076:12)

6/5/2020, 4:48:19 AM at Object.onceWrapper (events.js:286:20)

6/5/2020, 4:48:19 AM at IncomingMessage.emit (events.js:203:15)

6/5/2020, 4:48:19 AM at endReadableNT (_stream_readable.js:1143:12)

6/5/2020, 4:48:19 AM Response:6/5/2020, 4:48:19 AM {"timestamp":"2020-06-05T08:48:19.292Z","path":"/client/icontrol/delta","queryString":"spsId=100144615-1591346888975-2fe8f25a7e2a0e","method":"GET","fingerprint":"4c6ea7bd-928e-41f2-80ac-36c78122550a","errorCode":"UNKNOWN","exception":{"type":"DependentServiceException","message":"java.net.SocketTimeoutException: timeout"},"rootCause":{"type":"SocketException","message":"Socket closed"}}

6/5/2020, 4:48:19 AM [iControl Platform] Backing off live updates for 5 seconds.

**Comment by wylanswets** [comment]
Hey @cmb991 yes, this is a fairly common error you might see as comcast servers sometimes have those issues. It is just backing off from live updates for a short time then will try again.
